### ISSUE TITLE
Setting `show_small_image` to False breaks LazyImage for the whole page

### ISSUE THREAD

**Issue by danielsamuels** [dan-gamble/django-lazy-image#4]
Disabling `show_small_image` results in the small image element not being output, as expected:

https://github.com/dan-gamble/django-lazy-image/blob/a4b1f784aa0876139127fa166563673cfc866efc/django_lazy_image/templates/django_lazy_image/lazy-image.html#L6-L8

However, the JS will still try and remove this element, regardless of whether it exists or not:

https://github.com/dan-gamble/django-lazy-image/blob/a4b1f784aa0876139127fa166563673cfc866efc/assets/js/lazy-image.js#L15-L17

I think the above condition just needs to be changed to this:

```js
if (evt.propertyName === 'opacity' && this.smallImage) {
```

**Comment by dan-gamble** [comment]
Had to recently do this on CSP. Will fix it now 👍

**Comment by dan-gamble** [comment]
This is live under `0.3.2` now. (Pypi and npm)
